apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontcache.fullname" . }}-bucket-config
  labels:
    {{- include "frontcache.labels" . | nindent 4 }}
data:
  buckets.yaml: |
    default_provider: s3
    buckets: {}
